### PR TITLE
no arrows!

### PR DESCRIPTION
**Pull request by des-des**
Removed arrow functions from tests

### CODE REVIEW

**Comment by des-des** [comment]
:+1: merge me! Should work now...

**Comment by nelsonic** [comment]
Don't you just love it when the _standard_ is not universally implemented...? :wink: 
Thanks for fixing. :+1:

**Comment by des-des** [comment]
ugh 
image

**Comment by des-des** [comment]
ops.. I think this is a problem for tomorrow..

**Comment by nelsonic** [comment]
lol. indeed. not urgent at all. enjoy your evening! :+1:

**Pull request merged**
